In [33]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text  import CountVectorizer 
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier
import numpy as np

In [34]:
data=pd.read_csv("D:\\MACHINE LEARNING\\PROJECTS\\emotion detection\\emotion_dataset.csv")

In [35]:
data.head()

Unnamed: 0  Emotion                                               Text  \
0           0  neutral                                             Why ?    
1           1      joy    Sage Act upgrade on my to do list for tommorow.   
2           2  sadness  ON THE WAY TO MY HOMEGIRL BABY FUNERAL!!! MAN ...   
3           3      joy   Such an eye ! The true hazel eye-and so brill...   
4           4      joy  @Iluvmiasantos ugh babe.. hugggzzz for u .!  b...   

                                          Clean_Text  
0                                                NaN  
1                     Sage Act upgrade list tommorow  
2  WAY HOMEGIRL BABY FUNERAL MAN HATE FUNERALS SH...  
3  eye  true hazel eyeand brilliant  Regular feat...  
4    ugh babe hugggzzz u  babe naamazed nga ako e...

In [36]:
data.isnull().sum()

Unnamed: 0      0
Emotion         0
Text            0
Clean_Text    466
dtype: int64

In [37]:
data=data[["Emotion","Text"]]

In [38]:
data.head()

Emotion                                               Text
0  neutral                                             Why ? 
1      joy    Sage Act upgrade on my to do list for tommorow.
2  sadness  ON THE WAY TO MY HOMEGIRL BABY FUNERAL!!! MAN ...
3      joy   Such an eye ! The true hazel eye-and so brill...
4      joy  @Iluvmiasantos ugh babe.. hugggzzz for u .!  b...

In [39]:
data

Emotion                                               Text
0       neutral                                             Why ? 
1           joy    Sage Act upgrade on my to do list for tommorow.
2       sadness  ON THE WAY TO MY HOMEGIRL BABY FUNERAL!!! MAN ...
3           joy   Such an eye ! The true hazel eye-and so brill...
4           joy  @Iluvmiasantos ugh babe.. hugggzzz for u .!  b...
...         ...                                                ...
34787  surprise  @MichelGW have you gift! Hope you like it! It'...
34788       joy  The world didnt give it to me..so the world MO...
34789     anger                           A man robbed me today . 
34790      fear  Youu call it JEALOUSY, I call it of #Losing YO...
34791   sadness  I think about you baby, and I dream about you ...

[34792 rows x 2 columns]

In [40]:
data.describe

<bound method NDFrame.describe of         Emotion                                               Text
0       neutral                                             Why ? 
1           joy    Sage Act upgrade on my to do list for tommorow.
2       sadness  ON THE WAY TO MY HOMEGIRL BABY FUNERAL!!! MAN ...
3           joy   Such an eye ! The true hazel eye-and so brill...
4           joy  @Iluvmiasantos ugh babe.. hugggzzz for u .!  b...
...         ...                                                ...
34787  surprise  @MichelGW have you gift! Hope you like it! It'...
34788       joy  The world didnt give it to me..so the world MO...
34789     anger                           A man robbed me today . 
34790      fear  Youu call it JEALOUSY, I call it of #Losing YO...
34791   sadness  I think about you baby, and I dream about you ...

[34792 rows x 2 columns]>

In [41]:
data["Emotion"].value_counts()

Emotion
joy         11045
sadness      6722
fear         5410
anger        4297
surprise     4062
neutral      2254
disgust       856
shame         146
Name: count, dtype: int64

In [42]:
vectorizer=CountVectorizer(lowercase=True)

In [43]:
X=data["Text"]
Y=data["Emotion"]

In [44]:
X.shape


(34792,)

In [45]:
Y.shape

(34792,)

In [46]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,random_state=42,test_size=.3)

In [47]:
X_train.shape

(24354,)

In [48]:
X_test.shape

(10438,)

In [49]:
Y_train.shape

(24354,)

In [50]:
Y_test.shape

(10438,)

In [51]:
X_train_features=vectorizer.fit_transform(X_train)

In [52]:
print(X_train_features)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 329909 stored elements and shape (24354, 30142)>
  Coords	Values
  (0, 8034)	1
  (0, 28093)	1
  (0, 27061)	1
  (0, 10060)	1
  (0, 2698)	1
  (1, 4139)	1
  (1, 8117)	1
  (1, 6812)	1
  (1, 29577)	1
  (1, 3835)	1
  (1, 3158)	1
  (1, 6377)	1
  (1, 1574)	1
  (1, 871)	1
  (1, 26974)	1
  (1, 26513)	3
  (1, 9150)	1
  (1, 18975)	2
  (1, 28580)	1
  (1, 26678)	1
  (1, 22758)	1
  (1, 27184)	1
  (2, 28093)	1
  (2, 28896)	1
  (2, 14347)	1
  :	:
  (24351, 20485)	1
  (24351, 1299)	1
  (24351, 26870)	1
  (24351, 7370)	1
  (24351, 14324)	1
  (24351, 29558)	1
  (24351, 23241)	1
  (24351, 28768)	1
  (24352, 17999)	1
  (24352, 16878)	1
  (24352, 10932)	1
  (24352, 2460)	1
  (24352, 18104)	1
  (24352, 20454)	1
  (24352, 16293)	1
  (24352, 2768)	1
  (24353, 26974)	1
  (24353, 29152)	1
  (24353, 16878)	2
  (24353, 10304)	1
  (24353, 19298)	1
  (24353, 7940)	1
  (24353, 27482)	1
  (24353, 12689)	1
  (24353, 21351)	1


In [53]:
encoder=LabelEncoder()
input1=["joy",       
"sadness",  
"fear",     
"anger ",     
"surprise",   
"neutral" ,   
"disgust",      
"shame "]
encoded=encoder.fit_transform(input1)
encoded


array([3, 5, 2, 0, 7, 4, 1, 6])

0 -> Anger
1 -> disgust
2->fear
3-> joy
4->neutral
5->sadness
6->shame
7->surprise

In [54]:
Y_train=encoder.fit_transform(Y_train)

In [55]:
model=LinearRegression()
model.fit(X_train_features,Y_train)

LinearRegression()

In [56]:
Y_test=encoder.transform(Y_test)

In [57]:
X_test_features=vectorizer.transform(X_test)

In [58]:
Y_test

array([5, 0, 5, ..., 5, 0, 2])

In [59]:
Y_train

array([3, 3, 3, ..., 2, 5, 0])

In [60]:
prediction=model.predict(X_train_features)


In [61]:
prediction

array([3.35957804, 3.00081519, 3.31907956, ..., 1.9997714 , 4.9996755 ,
       3.5396478 ])

In [62]:
prediction=abs(prediction)

In [63]:
prediction

array([3.35957804, 3.00081519, 3.31907956, ..., 1.9997714 , 4.9996755 ,
       3.5396478 ])

In [64]:
prediction=np.floor(prediction)

In [65]:
prediction

array([3., 3., 3., ..., 1., 4., 3.])

In [66]:
Y_test

array([5, 0, 5, ..., 5, 0, 2])

In [67]:
model1=DecisionTreeClassifier()
model1.fit(X_train_features,Y_train)

DecisionTreeClassifier()

In [68]:
prediction=model1.predict(X_train_features)

In [69]:
accuracy=accuracy_score(prediction,Y_train)

In [70]:
accuracy

0.9980290711998029

In [71]:
prediction_test=model1.predict(X_test_features)


In [72]:
prediction_test

array([7, 4, 5, ..., 5, 4, 3])

In [73]:
accuracy_score(prediction_test,Y_test)

0.5232803219007472

In [74]:
input1=["Sage Act upgrade on my to do list for tommorow."]

In [75]:
input1_features=vectorizer.transform(input1)

In [76]:
input1_features

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 10 stored elements and shape (1, 30142)>

In [77]:
model1.predict(input1_features)

array([3])

In [78]:
import pickle 
with open("emotion_model.pkl","wb") as f:
  pickle.dump(model1,f)

In [79]:
with open("vectorizer.pkl","wb") as f1:
  pickle.dump(vectorizer,f1)

In [80]:
import numpy as np
import tensorflow

In [81]:
X.shape

(34792,)

In [86]:
X_train_features.shape

(24354, 30142)

In [87]:
Y_train.shape

(24354,)

In [88]:
Y_train[0:5]

array([3, 3, 3, 0, 3])

In [89]:
from tensorflow.keras.utils import to_categorical

y_train_one_hot = to_categorical(Y_train)


In [90]:
y_train_one_hot[0:5]

array([[0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.]])

In [91]:
y_train_one_hot.shape

(24354, 8)

In [95]:
from tensorflow.keras import layers, models
import tensorflow as tf 


In [103]:
X_train_features=X_train_features.toarray()

In [104]:
type(X_train_features)

numpy.ndarray

In [106]:
type(y_train_one_hot)

numpy.ndarray

In [114]:
neural_network = models.Sequential([
  layers.Dense(256,activation='relu',input_shape=(30142,)),
  layers.Dropout(0.5),
  layers.Dense(128,activation='relu'),
  layers.Dropout(0.5),
   layers.Dense(64,activation='relu'),
  layers.Dropout(0.5),
  layers.Dense(8,activation= 'softmax')
])

c:\Users\FVIN\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [115]:
neural_network.compile(
  optimizer="adam",
  loss="categorical_crossentropy",
  metrics=["accuracy"]

)

In [116]:
neural_network.fit(X_train_features,y_train_one_hot,epochs=5,validation_split=0.2)

Epoch 1/5
609/609 ━━━━━━━━━━━━━━━━━━━━ 52s 83ms/step - accuracy: 0.3342 - loss: 1.7468 - val_accuracy: 0.5724 - val_loss: 1.2602
Epoch 2/5
609/609 ━━━━━━━━━━━━━━━━━━━━ 42s 70ms/step - accuracy: 0.6324 - loss: 1.1226 - val_accuracy: 0.6134 - val_loss: 1.1222
Epoch 3/5
609/609 ━━━━━━━━━━━━━━━━━━━━ 45s 74ms/step - accuracy: 0.7696 - loss: 0.7571 - val_accuracy: 0.6208 - val_loss: 1.1504
Epoch 4/5
609/609 ━━━━━━━━━━━━━━━━━━━━ 46s 75ms/step - accuracy: 0.8359 - loss: 0.5370 - val_accuracy: 0.6186 - val_loss: 1.2824
Epoch 5/5
609/609 ━━━━━━━━━━━━━━━━━━━━ 48s 78ms/step - accuracy: 0.8892 - loss: 0.3784 - val_accuracy: 0.6177 - val_loss: 1.3673


In [117]:
y_test_onehot=to_categorical(Y_test)

In [118]:
less,accuracy=neural_network.evaluate(X_test_features,y_test_onehot)

327/327 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.6256 - loss: 1.3106


In [119]:
print(accuracy)

0.6227246522903442


In [120]:
input=["Sage Act upgrade on my to do list for tommorow."]
input_features=vectorizer.transform(input)


In [121]:
input_features.shape

(1, 30142)

In [122]:
prediction=neural_network.predict(input_features)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step


In [123]:
prediction

array([[1.1772798e-05, 2.1425426e-06, 1.1591317e-05, 9.9968445e-01,
        2.3086086e-06, 1.2326255e-04, 2.0417082e-10, 1.6462640e-04]],
      dtype=float32)

In [124]:
index=np.argmax(prediction)

In [126]:
print(index)

3


In [127]:
neural_network.save("neural_model.keras")