In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text  import CountVectorizer 
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier

KeyboardInterrupt: 

In [3]:
data=pd.read_csv("D:\\MACHINE LEARNING\\DATA SETS\\emotion_dataset.csv")

In [4]:
data.head()

Unnamed: 0  Emotion                                               Text  \
0           0  neutral                                             Why ?    
1           1      joy    Sage Act upgrade on my to do list for tommorow.   
2           2  sadness  ON THE WAY TO MY HOMEGIRL BABY FUNERAL!!! MAN ...   
3           3      joy   Such an eye ! The true hazel eye-and so brill...   
4           4      joy  @Iluvmiasantos ugh babe.. hugggzzz for u .!  b...   

                                          Clean_Text  
0                                                NaN  
1                     Sage Act upgrade list tommorow  
2  WAY HOMEGIRL BABY FUNERAL MAN HATE FUNERALS SH...  
3  eye  true hazel eyeand brilliant  Regular feat...  
4    ugh babe hugggzzz u  babe naamazed nga ako e...

In [5]:
data.isnull().sum()

Unnamed: 0      0
Emotion         0
Text            0
Clean_Text    466
dtype: int64

In [6]:
data=data[["Emotion","Text"]]

In [7]:
data.head()

Emotion                                               Text
0  neutral                                             Why ? 
1      joy    Sage Act upgrade on my to do list for tommorow.
2  sadness  ON THE WAY TO MY HOMEGIRL BABY FUNERAL!!! MAN ...
3      joy   Such an eye ! The true hazel eye-and so brill...
4      joy  @Iluvmiasantos ugh babe.. hugggzzz for u .!  b...

In [8]:
data

Emotion                                               Text
0       neutral                                             Why ? 
1           joy    Sage Act upgrade on my to do list for tommorow.
2       sadness  ON THE WAY TO MY HOMEGIRL BABY FUNERAL!!! MAN ...
3           joy   Such an eye ! The true hazel eye-and so brill...
4           joy  @Iluvmiasantos ugh babe.. hugggzzz for u .!  b...
...         ...                                                ...
34787  surprise  @MichelGW have you gift! Hope you like it! It'...
34788       joy  The world didnt give it to me..so the world MO...
34789     anger                           A man robbed me today . 
34790      fear  Youu call it JEALOUSY, I call it of #Losing YO...
34791   sadness  I think about you baby, and I dream about you ...

[34792 rows x 2 columns]

In [9]:
data.describe

<bound method NDFrame.describe of         Emotion                                               Text
0       neutral                                             Why ? 
1           joy    Sage Act upgrade on my to do list for tommorow.
2       sadness  ON THE WAY TO MY HOMEGIRL BABY FUNERAL!!! MAN ...
3           joy   Such an eye ! The true hazel eye-and so brill...
4           joy  @Iluvmiasantos ugh babe.. hugggzzz for u .!  b...
...         ...                                                ...
34787  surprise  @MichelGW have you gift! Hope you like it! It'...
34788       joy  The world didnt give it to me..so the world MO...
34789     anger                           A man robbed me today . 
34790      fear  Youu call it JEALOUSY, I call it of #Losing YO...
34791   sadness  I think about you baby, and I dream about you ...

[34792 rows x 2 columns]>

In [ ]:
data["Emotion"].value_counts()

joy         11045
sadness      6722
fear         5410
anger        4297
surprise     4062
neutral      2254
disgust       856
shame         146
Name: Emotion, dtype: int64

In [12]:
vectorizer=CountVectorizer(lowercase=True)

In [13]:
X=data["Text"]
Y=data["Emotion"]

In [14]:
X.shape


(34792,)

In [15]:
Y.shape

(34792,)

In [16]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,random_state=42,test_size=.3)

In [17]:
X_train.shape

(24354,)

In [18]:
X_test.shape

(10438,)

In [19]:
Y_train.shape

(24354,)

In [20]:
Y_test.shape

(10438,)

In [21]:
X_train_features=vectorizer.fit_transform(X_train)

In [22]:
print(X_train_features)

  (0, 8034)	1
  (0, 28093)	1
  (0, 27061)	1
  (0, 10060)	1
  (0, 2698)	1
  (1, 4139)	1
  (1, 8117)	1
  (1, 6812)	1
  (1, 29577)	1
  (1, 3835)	1
  (1, 3158)	1
  (1, 6377)	1
  (1, 1574)	1
  (1, 871)	1
  (1, 26974)	1
  (1, 26513)	3
  (1, 9150)	1
  (1, 18975)	2
  (1, 28580)	1
  (1, 26678)	1
  (1, 22758)	1
  (1, 27184)	1
  (2, 28093)	1
  (2, 28896)	1
  (2, 14347)	1
  :	:
  (24351, 20485)	1
  (24351, 1299)	1
  (24351, 26870)	1
  (24351, 7370)	1
  (24351, 14324)	1
  (24351, 29558)	1
  (24351, 23241)	1
  (24351, 28768)	1
  (24352, 17999)	1
  (24352, 16878)	1
  (24352, 10932)	1
  (24352, 2460)	1
  (24352, 18104)	1
  (24352, 20454)	1
  (24352, 16293)	1
  (24352, 2768)	1
  (24353, 26974)	1
  (24353, 29152)	1
  (24353, 16878)	2
  (24353, 10304)	1
  (24353, 19298)	1
  (24353, 7940)	1
  (24353, 27482)	1
  (24353, 12689)	1
  (24353, 21351)	1


In [24]:
encoder=LabelEncoder()
input1=["joy",       
"sadness",  
"fear",     
"anger ",     
"surprise",   
"neutral" ,   
"disgust",      
"shame "]
encoded=encoder.fit_transform(input1)
encoded


array([3, 5, 2, 0, 7, 4, 1, 6], dtype=int64)

0 -> Anger
1 -> disgust
2->fear
3-> joy
4->neutral
5->sadness
6->shame
7->surprise

In [25]:
Y_train=encoder.fit_transform(Y_train)

In [28]:
model=LinearRegression()
model.fit(X_train_features,Y_train)

LinearRegression()

In [29]:
Y_test=encoder.transform(Y_test)

In [30]:
X_test_features=vectorizer.transform(X_test)

In [31]:
Y_test

array([5, 0, 5, ..., 5, 0, 2])

In [32]:
Y_train

array([3, 3, 3, ..., 2, 5, 0])

In [35]:
prediction=model.predict(X_train_features)


In [37]:
prediction

array([3.35957804, 3.00081519, 3.31907956, ..., 1.9997714 , 4.9996755 ,
       3.5396478 ])

In [38]:
prediction=abs(prediction)

In [39]:
prediction

array([3.35957804, 3.00081519, 3.31907956, ..., 1.9997714 , 4.9996755 ,
       3.5396478 ])

In [41]:
prediction=np.floor(prediction)

In [42]:
prediction

array([3., 3., 3., ..., 1., 4., 3.])

In [43]:
Y_test

array([5, 0, 5, ..., 5, 0, 2])

In [44]:
model1=DecisionTreeClassifier()
model1.fit(X_train_features,Y_train)

DecisionTreeClassifier()

In [45]:
prediction=model1.predict(X_train_features)

In [46]:
accuracy=accuracy_score(prediction,Y_train)

In [47]:
accuracy

0.9980290711998029

In [48]:
prediction_test=model1.predict(X_test_features)


In [49]:
prediction_test

array([7, 4, 5, ..., 5, 4, 2])

In [51]:
accuracy_score(prediction_test,Y_test)

0.5252922015711822

In [52]:
input1=["Sage Act upgrade on my to do list for tommorow."]

In [53]:
input1_features=vectorizer.transform(input1)

In [ ]:
input1_features

<1x18148 sparse matrix of type '<class 'numpy.float64'>'
	with 9 stored elements in Compressed Sparse Row format>

In [54]:
model1.predict(input1_features)

array([3])

In [55]:
import pickle 
with open("emotion_model.pkl","wb") as f:
  pickle.dump(model1,f)

In [56]:
with open("vectorizer.pkl","wb") as f1:
  pickle.dump(vectorizer,f1)